/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Barcode APP'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    try{
                        alert('Trying...');
                        window.plugins.barcodeScanner.scan();
                        window.plugins.barcodeScanner.scan(function(result){
                            alert("We got a barcode\n"+"Result: "+result.text+"\n"+"Format: "+result.format+"\n"+"Cancelled: "+result.cancelled);
                        }, function(error) {
                            alert("Scanning failed: " + error);
                        }
                        );
                    }
                    catch(e){
                        alert('Scanning object not callable');
                        alert('Error'+e);
                    }
                },
                text: 'Scan'
            }
        ]
    }

});